# Numpy 실습 - 주석 달기
## 201923768 최준호
### Numpy ndarray 개요
------------

In [1]:
import numpy as np

In [2]:
# 1차원 배열 만들기 (Rank1) -> 3개의 데이터
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

# 2차원 배열 만들기 (Rank2) -> 2개의 로우 & 3개의 칼럼 -> 6개의 데이터
array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

# 2차원 배열 만들기 (Rank2) 1개의 로우 & 3개의 칼럼 -> 3개의 데이터
array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))
# 배열이 몇 차원인지 파악하기

array1: 1차원, array2: 2차원, array3:  2차원


In [4]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)
# list에서의 integer -> ndarray에서의 integer (같음)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [5]:
# int와 문자열이 섞여있을 경우 (유니코드 문자열로 변환)
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)
# int가 float와 섞여있을 경우 (float 형으로 변환)
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)
# 더 큰 데이터 타입이 존재할 경우, 더 큰 데이터 타입으로 변환된다는 것을 알 수 있음

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [6]:
array_int = np.array([1, 2, 3]) # int 형태
array_float = array_int.astype('float64') #float으로 변환시키기
print(array_float, array_float.dtype) # int가 float으로 변환 (x. '.'이 붙여있음(소수점 O))

array_int1= array_float.astype('int32') #int으로 변환시키기
print(array_int1, array_int1.dtype) # 그대로 int 유지

array_float1 = np.array([1.1, 2.1, 3.1]) # float 형태
array_int2= array_float1.astype('int32') #int으로 변환시키기
print(array_int2, array_int2.dtype) # float에서 int로 변환 ('.' 없어졌음(소수점 X))


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

In [7]:
sequence_array = np.arange(10) # 0~9까지 연속적인 값으로 구성된 1차원 ndarry 만들기
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape) # 유형과 차원의 크기 출력하기



[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [8]:
zero_array = np.zeros((3,2),dtype='int32') # 유형이 int이고 값이 모두 0인 배열 생성, 매개변수는 원하는 shape (row: 3 col:2)
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2)) # 값이 모두 1인 배열 생성, 매개변수는 원하는 shape (row: 3 col:2)
print(one_array)
print(one_array.dtype, one_array.shape) #int으로 설정안해서 float으로 출력

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### reshape

In [9]:
array1 = np.arange(10) # 0~9까지 연속적인 값으로 구성된 1차원 ndarry 만들기
print('array1:\n', array1)

array2 = array1.reshape(2,5) # row: 2 col: 5으로 재구성하기
print('array2:\n',array2)

array3 = array1.reshape(5,2) # row: 5 col: 2으로 재구성하기
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
array1.reshape(4,3) ## row: 4 col: 3으로 재구성하기 -> 안됨 왜냐하면 4*3=12 -> 2자리 빔

ValueError: cannot reshape array of size 10 into shape (4,3)

In [11]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5) #"-1" 활용하여 맞춤형 row 찾아내기
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1) #"-1" 활용하여 맞춤형 column 찾아내기
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [12]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4) # 알맞은 숫자의 row가 없어서 오류

ValueError: cannot reshape array of size 10 into shape (4)

In [13]:
# 3차원 ndarray 만들기
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### indexing

* 단일값 추출

In [14]:
# 1에서 부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value) #인덱스 위치 파악
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [15]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [16]:
# 데이터 값 변경하기
array1[0] = 9 # 첫번째 인덱스에서 9로 변경
array1[8] = 0 # 일곱번째 인덱스에서 8로 변경
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [17]:
array1d = np.arange(start=1, stop=10) # 1~9 ndarry
array2d = array1d.reshape(3,3) # row:3 col:3 2차원로 변환
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] ) # 1st row 1st col 위치의 값
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] ) # 1st row 2nd col 위치의 값
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] ) # 2nd row 1st col 위치의 값
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] ) # 3rd row 3rd col 위치의 값

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


* Slicing

In [18]:
array1 = np.arange(start=1, stop=10) # 1~9 ndarry
array3 = array1[0:3] # ndarry에서 첫 3개의 값 구성된 ndarry 출력
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [19]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3] # 1st~3rd 값의 ndarry 출력
print(array4)

array5 = array1[3:] #3rd~end 값의 ndarry 출력
print(array5)

array6 = array1[:] # all 값의 ndarry 출력
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [20]:
array1d = np.arange(start=1, stop=10) # 1~9 ndarry
array2d = array1d.reshape(3,3) # row:3 col:3 2차원로 변환
print('array2d:\n',array2d)
# left: row right: column의 위치 설정하여 출력
print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2]) # 1st~2nd row 1st~2nd col 2차원 ndarry
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3]) # 2st~3nd row 1st~3rd col 2차원 ndarry
print('array2d[1:3, :] \n', array2d[1:3, :]) # 2st~3nd row all 2차원 ndarry
print('array2d[:, :] \n', array2d[:, :]) # all row all col 2차원 ndarry
print('array2d[:2, 1:] \n', array2d[:2, 1:]) # first~2nd row 1st~end col 2차원 ndarry
print('array2d[:2, 0] \n', array2d[:2, 0]) # first~2nd row 1st col 2차원 ndarry

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [21]:
print(array2d[0]) # 첫 row 출력
print(array2d[1]) # 두번째 row 출력
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


* fancy indexing

In [22]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2] # row에 팬시 인덱싱 [0,1], col에서 index 2 적용
print('array2d[[0,1], 2] => ',array3.tolist()) 

array4 = array2d[[0,1], 0:2] # row에 팬시 인덱싱 [0,1], col에서 index 0:2 적용
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]] # row에 팬시 인덱싱 [0,1] 적용
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


* Boolean indexing

In [24]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [25]:
array1d > 5 # 5보다 크면 True 크지 않으면 False

array([False, False, False, False, False,  True,  True,  True,  True])

In [27]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes] # True 만 구성
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [26]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ] # 'index의 5~8에서 뽑기'
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬 – sort( )와 argsort( )

* 행렬 정렬

In [28]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)
# np.sort( )로 정렬 
sort_array1 = np.sort(org_array) # 정렬된 형태로 반환  (opposite)    
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)
# ndarray.sort( )로 정렬
sort_array2 = org_array.sort() # 정렬된 값으로 변환 (오름차순)
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)


원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [29]:
sort_array1_desc = np.sort(org_array)[::-1] # 정렬된 값으로 변환 (내림차순)
print ('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


In [30]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])
# 로우 방향으로 정렬
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)
# 칼럼 방향으로 정렬
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


* 정렬 행렬의 인덱스 반환

In [31]:
# np.argsort을 활용해 원본 행렬의 인덱스 출력
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [32]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1] #np.argsort에 [::-1] 더해 내림차순으로 인덱스 출력
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [13]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array) # np.argsort을 활용해 성적의 인덱스 출력
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc]) #인덱스에 해당되는 이름 출력

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 – 행렬 내적과 전치 행렬 구하기

* 행렬 내적

In [33]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B) #행렬과 행렬의 곱셈
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


* 전치 행렬

In [34]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A) # 전치행렬 구하기
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
